# Generated by Django 3.1.4 on 2021-02-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebChat', '0002_message_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='unread',
        ),
    ]
